site_name: History API
repo_url: https://github.com/leviobrabo/history-api
repo_name: leviobrabo/history-api
edit_uri: tree/main/docs

theme:
    name: material
    favicon: assets/flavicon.png
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.tooltips
        - navigation.tabs
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tracking
        - toc.integrate
        - toc.follow
        - navigation.top
        - search.suggest
        - search.share
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/link
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: indigo
          toggle:
              icon: material/toggle-switch-off
              name: Switch to system preference
    font:
        text: Roboto
        code: Roboto Mono
    icon:
    logo: assets/logo.png

markdown_extensions:
    - attr_list

plugins:
    - mkdocstrings:
          handlers:
              python:
                  paths: [history_api]
    - search:
          separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
    status:
        new: Recently added
        deprecated: Deprecated
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/leviobrabo
        - icon: fontawesome/brands/telegram
          link: https://t.me/leviobrabo

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - History: index.md
  - Getting started:
    - Installation: getting-started.md
    - How to use: how-to-use.md
    - Language: language.md
  - API: 
     - Events:
        - All historical events: API/Events/events.md
        - Historical events by month: API/Events/events_month_day.md
        - Historical events by month and day: API/Events/events_month.md
     - Presidents:
        - All presidents: API/Presidents/presidents.md
        - Presidents by ID: API/Presidents/presidents_id.md
        - Presidents by ID ranges: API/Presidents/presidents_range_id.md
        - Presidents by location: API/Presidents/presidents_location.md
        - Presidents by name: API/Presidents/presidents_name.md


copyright: |
    &copy; 2023 <a href="https://github.com/leviobrabo" target="_blank" rel="noopener">Levi</a>
