LANGUAGES = {
    "ar": "Arabic",
    "cs": "Czech",
    "de": "Germany",
    "en": "English",
    "es": "Spain",
    "fr": "France",
    "hi": "Hindi",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "pl": "Polish",
    "pt": "Portuguese",
    "ru": "Russian",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "vi": "Vietnamese",
    "zh": "Chinese"
}
